= Jequire - A Requirements Manager
Bill Turner
:toc:
:toc-placement!:

toc::[]

== Summary
This project has been long abandoned.  It was started when I was first learning Java (I think with 1.1.3), about 1996 if I recall correctly. I had largely been doing COBOL development up to that point in time professionally, but also had done some work with Smalltalk and C/C++.

This was meant to be an implementation of a sort of the Volere Requirements Template, as well as additional features that I understood from my study of Requirements Engineering around that time. Like most in the industry, I had not heard anything of Agile yet. It wasn't until late 1999 when Kent Beck published an article on _eXtreme Programming_ that I first heard of such practices and introduced them to the team at a startup of which I was the technical leader.

Anyway... take from this whatever you wish. I am keeping it just for historical reference

== Requirements Engineering Reading List

Some books on Requirements Engineering I found enlightening - with maybe a few other books that seem somehow relevant. I think most BAs would do well to understand the rigor involved in good requirements. That does not mean, though, that I any longer believe in _Big Requirements Up Front_ for most projects, not that the practice of *Waterfall* was anything like so many people believe.

There is no order here.

. Weinberg, G. (199x). Exploring Requirements: Quality Before Design.
